[build]
publish = "out"
command = "npm run build"
environment = { NODE_VERSION = "12" }

[[plugins]]
package = "@netlify/plugin-sitemap"
    [plugins.inputs]

    exclude = [
    '**/**/privacy-policy',
    '**/**/404',
    '**/**/thank-you',
    ]
